name: cuahanghoa_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.15.1
  animations: ^2.0.11
  url_launcher: ^6.3.0
  firebase_auth: ^6.1.1
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3
  webview_flutter: ^4.4.1
  pay: ^3.2.1
  lottie: ^3.3.2
  google_fonts: ^6.3.2
  uuid: ^4.5.1
  cloudinary_public: ^0.23.1
  firebase_messaging: ^16.0.3
  fl_chart: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - assets/logo/
      - assets/lottie/success.json



